### ISSUE TITLE
upgrade PF5 from @openshift-assisted/ui-lib component

### ISSUE THREAD

**Issue by Ginxo** [openshift-assisted/assisted-installer-ui#2470]
We recently upgraded OCM-UI application to PF5 and since OCM-UI is using `@openshift-assisted/ui-lib@^2.29.0` PF4 and PF5 libraries are co-living and generating estrange behaviours or console errors

```
"@openshift-assisted/ui-lib@2.29.0":
  version "2.29.0"
  dependencies:
...
    "@patternfly/react-core" "^4.168.8"
```

See for instance https://issues.redhat.com/browse/OCMUI-124

Is this upgrading on your backlog? any due date for it?

Many thanks!

**Comment by ammont82** [comment]
We are working on it.
This is the task related: https://issues.redhat.com/browse/MGMT-16500

**Comment by ammont82** [comment]
PR: https://github.com/openshift-assisted/assisted-installer-ui/pull/2477

**Comment by ammont82** [comment]
@Ginxo Assisted UI Lib 2.31.7 was deployed to production and includes the change to PF5 styles.

**Comment by Ginxo** [comment]
thanks @ammont82 I see openshift-assisted/ui-lib still depends on @openshift-console/dynamic-plugin-sdk -> @patternfly/react-core:4.168.8
Any plan for this? 

see information from yarn.lock
```
...
"@openshift-assisted/ui-lib@2.31.7":
  version "2.31.7"
  resolved "https://registry.yarnpkg.com/@openshift-assisted/ui-lib/-/ui-lib-2.31.7.tgz#82a216118512478685d469feabf9dde29340319f"
  integrity sha512-645yI89Lat1CsJukslMWFdqj3MFYViCMCR/y3Nz2ziEvHq7l1eXeA6pl0zwN6P7nQbffTX5SssvIY7IT31tsPg==
  dependencies:
    "@openshift-assisted/locales" "2.31.7"
    "@openshift-assisted/types" "2.31.7"
    "@openshift-console/dynamic-plugin-sdk" "0.0.3"
....
```

thanks @ammont82

**Comment by ammont82** [comment]
I'll take a look @Ginxo
