### ISSUE TITLE
Doc URL contains hard-coded version number

### ISSUE THREAD

**Issue by apinnick** [openshift-assisted/assisted-installer-ui#2606]
https://github.com/openshift-assisted/assisted-installer-ui/blob/322630e1276b254cfc10619d749f98cd5e46bf45/libs/ui-lib/lib/common/config/docs_links.ts#L62C1-L62C261

This URL will break if the doc version number changes and a specific redirect is not in place. 

Please use an attribute for the version number to avoid maintenance issues.

**Comment by ammont82** [comment]
@apinnick are you talking about the year in the URL?
https://access.redhat.com/documentation/en-us/assisted_installer_for_openshift_container_platform/**2024**/html/installing_openshift_container_platform_with_the_assisted_installer/expanding-the-cluster#checking-for-multiple-architectures_expanding-the-cluster

**Comment by apinnick** [comment]
@ammont82 Yes

**Comment by ammont82** [comment]
@apinnick and what do you suggest?Change the year dinamically?

**Comment by apinnick** [comment]
I thought you could do it like you do in line 8:

export const ASSISTED_INSTALLER_DOCUMENTATION_LINK = `https://access.redhat.com/documentation/en-us/assisted_installer_for_openshift_container_platform/${getYearForAssistedInstallerDocumentationLink()}/html/installing_openshift_container_platform_with_the_assisted_installer/index`;

**Comment by ammont82** [comment]
Jira task: https://issues.redhat.com/browse/MGMT-18242

**Comment by ammont82** [comment]
Now in production: https://console.redhat.com/openshift/assisted-installer/clusters/~new
