### ISSUE TITLE
Console link (pull secret) among doc links

### ISSUE THREAD

**Issue by apinnick** [openshift-assisted/assisted-installer-ui#2607]
https://github.com/openshift-assisted/assisted-installer-ui/blob/322630e1276b254cfc10619d749f98cd5e46bf45/libs/ui-lib/lib/common/config/docs_links.ts#L16

This link looks like it does not belong in docs_links.ts.

**Comment by ammont82** [comment]
Now in production: https://console.redhat.com/openshift/assisted-installer/clusters/~new
