### ISSUE TITLE
OCP network docs link

### ISSUE THREAD

**Issue by apinnick** [openshift-assisted/assisted-installer-ui#2609]
https://github.com/openshift-assisted/assisted-installer-ui/blob/322630e1276b254cfc10619d749f98cd5e46bf45/libs/ui-lib/lib/common/config/docs_links.ts#L27C1-L29C120

Replace docs.openshift.com with docs.redhat.com link: https://docs.redhat.com/en/documentation/openshift_container_platform/4.15/html/installing/installing-on-bare-metal#installation-network-user-infra_installing-bare-metal

**Comment by ammont82** [comment]
Jira ticket: https://issues.redhat.com/browse/MGMT-18244

**Comment by ammont82** [comment]
Now in production: https://console.redhat.com/openshift/assisted-installer/clusters/~new
