### ISSUE TITLE
"Approving cert-signing requests" link

### ISSUE THREAD

**Issue by apinnick** [openshift-assisted/assisted-installer-ui#2610]
https://github.com/openshift-assisted/assisted-installer-ui/blob/322630e1276b254cfc10619d749f98cd5e46bf45/libs/ui-lib/lib/common/config/docs_links.ts#L37C1-L39C135

Use this: https://docs.redhat.com/en/documentation/openshift_container_platform/4.15/html/installing/installing-on-any-platform#installation-approve-csrs_installing-platform-agnostic

**Comment by ammont82** [comment]
Now in production: https://console.redhat.com/openshift/assisted-installer/clusters/~new
