### ISSUE TITLE
ACM doc link

### ISSUE THREAD

**Issue by apinnick** [openshift-assisted/assisted-installer-ui#2611]
https://github.com/openshift-assisted/assisted-installer-ui/blob/322630e1276b254cfc10619d749f98cd5e46bf45/libs/ui-lib/lib/common/config/docs_links.ts#L45C1-L45C29

Change domain from `access.redhat.com` to `docs.redhat.com`

**Comment by ammont82** [comment]
Jira ticket: https://issues.redhat.com/browse/MGMT-18246

**Comment by ammont82** [comment]
Now in production: https://console.redhat.com/openshift/assisted-installer/clusters/~new
