### ISSUE TITLE
Custom manifests link

### ISSUE THREAD

**Issue by apinnick** [openshift-assisted/assisted-installer-ui#2612]
https://github.com/openshift-assisted/assisted-installer-ui/blob/322630e1276b254cfc10619d749f98cd5e46bf45/libs/ui-lib/lib/common/config/docs_links.ts#L54C4-L54C108

`https://docs.redhat.com/en/documentation/openshift_container_platform/4.15/html/installing/installation-configuration#installation-special-config-kargs_installing-customizing`

**Comment by ammont82** [comment]
Jira ticket: https://issues.redhat.com/browse/MGMT-18247

**Comment by ammont82** [comment]
Now in production: https://console.redhat.com/openshift/assisted-installer/clusters/~new
