### ISSUE TITLE
Operators page links

### ISSUE THREAD

**Issue by apinnick** [openshift-assisted/assisted-installer-ui#2613]
https://github.com/openshift-assisted/assisted-installer-ui/blob/322630e1276b254cfc10619d749f98cd5e46bf45/libs/ui-lib/lib/common/config/docs_links.ts#L72C1-L87C93

I recommend that you replace the individual links to the various docs with a link to the new section on Operators in the AI guide: 

[Customizing your installation](https://docs.redhat.com/en/documentation/assisted_installer_for_openshift_container_platform/2024/html-single/installing_openshift_container_platform_with_the_assisted_installer/index#customizing-installation_about-ai)

If this is acceptable, I will create a permalink for the UI in the AI user guide.

**Comment by ammont82** [comment]
Jira ticket: https://issues.redhat.com/browse/MGMT-18248

**Comment by ammont82** [comment]
Now in production: https://console.redhat.com/openshift/assisted-installer/clusters/~new
