### ISSUE TITLE
MCE link - resource requirements

### ISSUE THREAD

**Issue by apinnick** [openshift-assisted/assisted-installer-ui#2614]
https://github.com/openshift-assisted/assisted-installer-ui/blob/322630e1276b254cfc10619d749f98cd5e46bf45/libs/ui-lib/lib/common/config/docs_links.ts#L78C1-L82C41

Because multicluster engine has specific additional resource requirements, depending on the storage operators and cluster type, I recommend that you create a link to this section: [Resource requirements](https://docs.redhat.com/en/documentation/assisted_installer_for_openshift_container_platform/2024/html-single/installing_openshift_container_platform_with_the_assisted_installer/index#resource_requirements)

**Comment by ammont82** [comment]
Jira ticket: https://issues.redhat.com/browse/MGMT-18249

**Comment by ammont82** [comment]
Now in production: https://console.redhat.com/openshift/assisted-installer/clusters/~new
