### ISSUE TITLE
Nutanix post-install config

### ISSUE THREAD

**Issue by apinnick** [openshift-assisted/assisted-installer-ui#2619]
https://github.com/openshift-assisted/assisted-installer-ui/blob/0b60c3bbfc98f4de0ca60b8c104c3375a92e4921/libs/ui-lib/lib/common/config/docs_links.ts#L48

https://docs.redhat.com/en/documentation/assisted_installer_for_openshift_container_platform/2024/html-single/installing_openshift_container_platform_with_the_assisted_installer/index#nutanix-post-installation-configuration_installing-on-nutanix

**Comment by ammont82** [comment]
Jira ticket: https://issues.redhat.com/browse/MGMT-18265

**Comment by ammont82** [comment]
Now in production: https://console.redhat.com/openshift/assisted-installer/clusters/~new
