### ISSUE TITLE
Fix AI SaaS URL

### ISSUE THREAD

**Issue by apinnick** [openshift-assisted/assisted-installer-ui#2630]
https://github.com/openshift-assisted/assisted-installer-ui/blob/a47abde6695fef618ffbbc9c520d6ced6d9883c8/libs/ui-lib/lib/common/config/docs_links.ts#L10

This needs to be converted to the docs.redhat.com URL.

**Comment by ammont82** [comment]
https://github.com/openshift-assisted/assisted-installer-ui/pull/2631

**Comment by ammont82** [comment]
@apinnick one question, we have more links with access.redhat.com in the file. Do we need to change also?

**Comment by apinnick** [comment]
> @apinnick one question, we have more links with access.redhat.com in the file. Do we need to change also?

That would probably be a good idea.

**Comment by ammont82** [comment]
@apinnick but it seems not all links works in docs.redhat.com.

**Comment by ammont82** [comment]
It will be changed in 2.33 version
